### ISSUE TITLE
Please describe what needs to be done to add another model / controller

### ISSUE THREAD

**Issue by supersexy** [tbreuss/pingcrm-yii2#4]
This is  an interesting project! It would be very interesting to read about what needs to be done to add another model / controller, just to understand what is needed on top of the typical yii workflow. It would be great if you cound write down just a few sentences - or make a series of very clean commits so everybody can understand how to add more entities. Thank you very much!

**Comment by tbreuss** [comment]
I just added some information here 985f1a05433b36ee02b47d27d11b2076b24917a3.

This is a demo project which is a clone of another demo project. In order to work it uses different adapters for the backend and frontend. Meaning, you should follow the instructions here:

Official Inertia website with helpful information:
- https://inertiajs.com

Inertia Vue.js adapter used in this project:
- https://github.com/inertiajs/inertia-vue

Inertial Yii2 adapter used in this project:
- https://github.com/tbreuss/yii2-inertia
